require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/*'
    - 'storage/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'public/*'
    - 'coverage/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe','context']


Style/RedundantFetchBlock:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false
  