version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers-legacy
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: nastya
          POSTGRES_DB: rails_api_flow_auth_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Install dependencies
          command: |
            bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rspec
