version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers-legacy
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: nastya
          POSTGRES_DB: rails_api_flow_auth_test          
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

  
      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate

      - run:
          name: Run tests
          command: bundle exec rspec                     
