version: 2.1
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails

    docker:
      - image: circleci/ruby:2.7.2-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test      
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: nastya
          POSTGRES_DB: rails_api_flow_auth_test          
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true
      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle     

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate


      - run:
          name: Run tests
          command: bundle exec rspec  

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
                   
