default: &default
  adapter: postgresql
  encoding: unicode  
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.config[:database][:postgresql_user] %>
  password: <%= Rails.application.credentials.config[:database][:postgresql_password] %>

development:
  <<: *default
  database: rails_api_flow_auth_development

 
test:
  <<: *default
  database: rails_api_flow_auth_test


production:
  <<: *default
  database: rails_api_flow_auth_production

